name: SPFx CI

on:
  pull_request:
    paths:
      - spfx/**
      - .github/workflows/spfx-ci.yaml
  push:
    branches:
      - main
    paths:
      - spfx/**
      - .github/workflows/spfx-ci.yaml

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: spfx/.nvmrc
          cache: npm
          cache-dependency-path: spfx/package-lock.json
      - run: npm install
        working-directory: spfx
      - run: npm run ship
        working-directory: spfx
